@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Feb 04 10:46:09 -0600 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim Comp_Unit_TestBench_behav -key {Behavioral:sim_1:Functional:Comp_Unit_TestBench} -tclbatch Comp_Unit_TestBench.tcl -view C:/Users/ojb0020/Downloads/EENG 5560 - Reconfigurable Computing/Homework/Homework 1/Computation_Unit/Comp_Unit_TestBench_Test_2.wcfg -log simulate.log"
call xsim  Comp_Unit_TestBench_behav -key {Behavioral:sim_1:Functional:Comp_Unit_TestBench} -tclbatch Comp_Unit_TestBench.tcl -view C:/Users/ojb0020/Downloads/EENG 5560 - Reconfigurable Computing/Homework/Homework 1/Computation_Unit/Comp_Unit_TestBench_Test_2.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
