@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 05 12:42:29 -0600 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim ARCA_Logic_Array_Test_Bench_behav -key {Behavioral:sim_1:Functional:ARCA_Logic_Array_Test_Bench} -tclbatch ARCA_Logic_Array_Test_Bench.tcl -view C:/Users/ojb0020/Downloads/EENG 5560 - Reconfigurable Computing/Homework/Homework 2/ARCA_Logic_Array/ARCA_Logic_Array_Test_Bench_behav.wcfg -log simulate.log"
call xsim  ARCA_Logic_Array_Test_Bench_behav -key {Behavioral:sim_1:Functional:ARCA_Logic_Array_Test_Bench} -tclbatch ARCA_Logic_Array_Test_Bench.tcl -view C:/Users/ojb0020/Downloads/EENG 5560 - Reconfigurable Computing/Homework/Homework 2/ARCA_Logic_Array/ARCA_Logic_Array_Test_Bench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
